//constants for ActionTypes
export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';


// calendar
export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCES';
export const SELECT_CALENDAR_EVENT =  'SELECT_CALENDAR_EVENT';
export const LOAD_CALENDAR_EVENT_SUCCESS = 'LOAD_CALENDAR_EVENT_SUCCESS';